icontheme: Recolor symbolic nodes
These nodes are very simple, so we can just walk them and replace
the colors. In order to work with the color-matrix approach, the
nodes have the following colors after conversion:

foreground: 0,0,0,1
error:      0,0,1,1
warning:    0,1,0,1
success:    1,0,0,1