quartz: fix compilation problem introduced by !5648
Including plain "gdkquartz.h" ends with compilation error:

```
../gtk/gtkfilechoosernativequartz.c:43:10: fatal error: 'gdkquartz.h' file not found
#include "gdkquartz.h"
         ^~~~~~~~~~~~~
1 error generated.

```