tests: fix libtestutils build under Windows.
It shows linker warnings with clang and msvc, but fails with gcc:
undefined reference to `__imp_gsk_render_node_serialize'
...

Pass GDK_STATIC_COMPILATION so that dllimport isn't used for the static
lib.

Part-of: <https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/9557>