docs: trivial build fix
The error was:
gtk3-scan.c:193: undefined reference to `gtk_shortcuts_label_get_type'
collect2: error: ld returned 1 exit status

It's since commit 7543cd8ce419a4d660f0ff7614f0c6e1cac81804, which made
the GtkShortcutLabel class public.