icontheme: Recolor symbolic nodes
These nodes are very simple, so we can just walk them and replace
the colors. In order to work with the color-matrix approach, the
nodes have the following colors after conversion:

foreground: 0,0,0,α
error:      0,0,1,α
warning:    0,1,0,α
success:    1,0,0,α

Note that the alpha can be different since symbolic icons do use
fill-opacity. We are careful to preserve the alpha, and ignore it
for the matching.

Part-of: <https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/8547>