win32: fix a missing-braces warning
error: missing braces around initializer [-Werror=missing-braces]

Part-of: <https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/9208>